const historicalEvents = {
    1936: "Alan Turing presents the concept of the Turing Machine in his paper 'On Computable Numbers'.",
    1946: "ENIAC, the first general-purpose electronic computer, is unveiled at the University of Pennsylvania.",
    1947: "The transistor is invented at Bell Labs by William Shockley, John Bardeen, and Walter Brattain.",
    1954: "FORTRAN, the first high-level programming language, is developed by IBM.",
    1969: "ARPANET, the precursor to the internet, is created.",
    1971: "The first microprocessor, the Intel 4004, is released.",
    1972: "C programming language is created by Dennis Ritchie at Bell Labs.",
    1973: "Xerox PARC develops the Alto, the first computer with a graphical user interface.",
    1975: "Microsoft is founded by Bill Gates and Paul Allen.",
    1976: "Apple Computer is founded by Steve Jobs and Steve Wozniak.",
    1981: "IBM releases the IBM PC, which becomes the standard for personal computing.",
    1983: "TCP/IP becomes the standard protocol for ARPANET, marking the birth of the modern internet.",
    1985: "The first version of Microsoft Windows is released.",
    1989: "Tim Berners-Lee proposes the World Wide Web at CERN.",
    1991: "Linux is released by Linus Torvalds.",
    1993: "Mosaic, the first popular web browser, is released.",
    1995: "JavaScript is created by Brendan Eich at Netscape.",
    1998: "Google is founded by Larry Page and Sergey Brin.",
    2001: "The first version of Wikipedia is launched.",
    2007: "Apple releases the first iPhone, revolutionizing mobile computing.",
    2008: "Bitcoin is introduced by Satoshi Nakamoto.",
    2010: "Instagram is launched, popularizing mobile photo sharing.",
    2012: "The Raspberry Pi, a credit-card sized computer, is released.",
    2015: "TensorFlow, Google's open-source machine learning framework, is released.",
    2016: "AlphaGo defeats world champion Go player Lee Sedol.",
    2017: "The first commercial quantum computer is announced by IBM.",
    2019: "GitHub announces the Arctic Code Vault to preserve open source software.",
    2020: "The COVID-19 pandemic accelerates the adoption of remote work and cloud computing.",
    2022: "ChatGPT is released by OpenAI, marking a breakthrough in AI language models.",
    2023: "The first commercial quantum computer with over 1000 qubits is announced."
}; 