const historicalEvents = {
    1936: "Alan Turing publishes 'On Computable Numbers' introducing the Turing Machine concept.",
    1946: "ENIAC, the first general-purpose electronic computer, is unveiled at the University of Pennsylvania.",
    1947: "William Shockley, John Bardeen, and Walter Brattain invent the transistor at Bell Labs.",
    1950: "Alan Turing proposes the Turing Test in his paper 'Computing Machinery and Intelligence'.",
    1954: "FORTRAN, the first high-level programming language, is developed by IBM.",
    1958: "Jack Kilby and Robert Noyce independently invent the integrated circuit.",
    1962: "Spacewar!, the first video game, is created by Steve Russell at MIT.",
    1969: "ARPANET, the precursor to the Internet, is established between UCLA and Stanford.",
    1970: "UNIX operating system is created by Ken Thompson and Dennis Ritchie at Bell Labs.",
    1971: "Intel releases the first microprocessor, the Intel 4004.",
    1972: "C programming language is created by Dennis Ritchie at Bell Labs.",
    1973: "Xerox PARC develops the Alto, the first computer with a graphical user interface.",
    1975: "Microsoft is founded by Bill Gates and Paul Allen.",
    1976: "Apple Computer is founded by Steve Jobs and Steve Wozniak.",
    1977: "Apple II, the first mass-produced personal computer, is released.",
    1981: "IBM introduces the IBM PC, setting the standard for personal computers.",
    1983: "TCP/IP becomes the standard protocol for ARPANET, marking the birth of the modern Internet.",
    1984: "Apple releases the Macintosh, the first successful mass-market personal computer with a GUI.",
    1985: "C++ programming language is created by Bjarne Stroustrup.",
    1989: "Tim Berners-Lee invents the World Wide Web at CERN.",
    1990: "Python programming language is created by Guido van Rossum.",
    1991: "Linus Torvalds releases the first version of Linux.",
    1993: "Mosaic, the first popular web browser, is released by NCSA.",
    1994: "Amazon.com is founded by Jeff Bezos.",
    1995: "JavaScript is created by Brendan Eich at Netscape.",
    1996: "Google is founded by Larry Page and Sergey Brin.",
    1998: "PayPal is founded, revolutionizing online payments.",
    2001: "Wikipedia is launched by Jimmy Wales and Larry Sanger.",
    2004: "Facebook is founded by Mark Zuckerberg at Harvard.",
    2005: "YouTube is founded by Chad Hurley, Steve Chen, and Jawed Karim.",
    2007: "Apple releases the iPhone, revolutionizing mobile computing.",
    2008: "Bitcoin, the first cryptocurrency, is introduced by Satoshi Nakamoto.",
    2009: "WhatsApp is founded by Jan Koum and Brian Acton.",
    2010: "Instagram is founded by Kevin Systrom and Mike Krieger.",
    2011: "IBM's Watson defeats human champions on Jeopardy!",
    2012: "Raspberry Pi, the first affordable single-board computer, is released.",
    2014: "Microsoft acquires Minecraft for $2.5 billion.",
    2015: "TensorFlow, Google's open-source machine learning framework, is released.",
    2016: "AlphaGo defeats world champion Lee Sedol in Go.",
    2017: "Bitcoin reaches $20,000 for the first time.",
    2018: "GitHub is acquired by Microsoft for $7.5 billion.",
    2019: "Google achieves quantum supremacy with their 53-qubit processor.",
    2020: "COVID-19 pandemic accelerates digital transformation worldwide.",
    2021: "NFTs become mainstream with record-breaking sales.",
    2022: "ChatGPT is released by OpenAI, revolutionizing AI interaction.",
    2023: "Apple Vision Pro is announced, marking a new era in spatial computing.",
    2024: "Google's Gemini Ultra AI model achieves human-level performance across multiple domains.",
    2025: "First commercial quantum computer with over 1000 qubits becomes available."
}; 